import PredictTopic from '../models/predict-topic';

const prebuilt = [
  [
    { topic: '健康', language: 'zh' },
    { topic: '家庭', language: 'zh' },
    { topic: '社交关系', language: 'zh' },
    { topic: '学业', language: 'zh' },
    { topic: '旅行', language: 'zh' },
    { topic: '精神成长', language: 'zh' },
    { topic: '个人成长', language: 'zh' },
    { topic: '情感平衡', language: 'zh' },
    { topic: '自信与自尊', language: 'zh' },
    { topic: '内在平静', language: 'zh' },
    { topic: '社会影响力', language: 'zh' },
    { topic: '人际沟通', language: 'zh' },
    { topic: '心灵连接', language: 'zh' },
    { topic: '存在意义', language: 'zh' },
    { topic: '灵感与创造力', language: 'zh' },
    { topic: '心理与情绪健康', language: 'zh' },
    { topic: '人际关系', language: 'zh' },
    { topic: '教育发展', language: 'zh' },
    { topic: '健身与体能', language: 'zh' },
    { topic: '时间管理', language: 'zh' },
    { topic: '自我认知', language: 'zh' },
    { topic: '精神探索', language: 'zh' },
    { topic: '社会适应能力', language: 'zh' },
    { topic: '自我表达', language: 'zh' },
    { topic: '职业满足度', language: 'zh' },
    { topic: '理财能力', language: 'zh' },
    { topic: '家庭和谐', language: 'zh' },
    { topic: '冒险与探索', language: 'zh' },
    { topic: '心灵治愈', language: 'zh' },
    { topic: '才艺发展', language: 'zh' },
    { topic: '创业机会', language: 'zh' },
    { topic: '客观实现', language: 'zh' },
    { topic: '平衡与调和', language: 'zh' },
    { topic: '社区参与', language: 'zh' },
    { topic: '家庭支持', language: 'zh' },
    { topic: '内在智慧', language: 'zh' },
    { topic: '情感表达', language: 'zh' },
    { topic: '环境意识', language: 'zh' },
    { topic: '身心调和', language: 'zh' },
    { topic: '灵性导向', language: 'zh' },
    { topic: '健康习惯', language: 'zh' },
    { topic: '团队合作', language: 'zh' },
    { topic: '自我关爱', language: 'zh' },
    { topic: '敬业精神', language: 'zh' },
  ],
  [
    { topic: 'Health', language: 'en' },
    { topic: 'Family', language: 'en' },
    { topic: 'Social Relationships', language: 'en' },
    { topic: 'Academic Pursuits', language: 'en' },
    { topic: 'Travel', language: 'en' },
    { topic: 'Mental Growth', language: 'en' },
    { topic: 'Personal Development', language: 'en' },
    { topic: 'Emotional Balance', language: 'en' },
    { topic: 'Confidence and Self Esteem', language: 'en' },
    { topic: 'Inner Peace', language: 'en' },
    { topic: 'Social Impact', language: 'en' },
    { topic: 'Interpersonal Communication', language: 'en' },
    { topic: 'Spiritual Connection', language: 'en' },
    { topic: 'Sense of Purpose', language: 'en' },
    { topic: 'Inspiration and Creativity', language: 'en' },
    { topic: 'Psychological and Emotional Well being', language: 'en' },
    { topic: 'Interpersonal Relationships', language: 'en' },
    { topic: 'Educational Development', language: 'en' },
    { topic: 'Fitness and Physical Well being', language: 'en' },
    { topic: 'Time Management', language: 'en' },
    { topic: 'Self awareness', language: 'en' },
    { topic: 'Spiritual Exploration', language: 'en' },
    { topic: 'Social Adaptability', language: 'en' },
    { topic: 'Self expression', language: 'en' },
    { topic: 'Career Satisfaction', language: 'en' },
    { topic: 'Financial Literacy', language: 'en' },
    { topic: 'Family Harmony', language: 'en' },
    { topic: 'Adventure and Exploration', language: 'en' },
    { topic: 'Spiritual Healing', language: 'en' },
    { topic: 'Talent Development', language: 'en' },
    { topic: 'Entrepreneurial Opportunities', language: 'en' },
    { topic: 'Objective Achievement', language: 'en' },
    { topic: 'Balance and Harmony', language: 'en' },
    { topic: 'Community Engagement', language: 'en' },
    { topic: 'Family Support', language: 'en' },
    { topic: 'Intrinsic Wisdom', language: 'en' },
    { topic: 'Emotional Expression', language: 'en' },
    { topic: 'Environmental Awareness', language: 'en' },
    { topic: 'Mind Body Alignment', language: 'en' },
    { topic: 'Spiritual Guidance', language: 'en' },
    { topic: 'Healthy Habits', language: 'en' },
    { topic: 'Team Collaboration', language: 'en' },
    { topic: 'Self Care', language: 'en' },
    { topic: 'Dedication to Work', language: 'en' },
  ],
  [
    { topic: '健康', language: 'ja' },
    { topic: '家庭', language: 'ja' },
    { topic: '社会関係', language: 'ja' },
    { topic: '学業', language: 'ja' },
    { topic: '旅行', language: 'ja' },
    { topic: '精神的成長', language: 'ja' },
    { topic: '個人成長', language: 'ja' },
    { topic: '感情のバランス', language: 'ja' },
    { topic: '自信と自尊心', language: 'ja' },
    { topic: '内なる平和', language: 'ja' },
    { topic: '社会的影響力', language: 'ja' },
    { topic: '人間関係', language: 'ja' },
    { topic: '霊的な繋がり', language: 'ja' },
    { topic: '目的の感覚', language: 'ja' },
    { topic: 'インスピレーションと創造性', language: 'ja' },
    { topic: '心理的・感情的健康', language: 'ja' },
    { topic: '人間関係', language: 'ja' },
    { topic: '教育的発展', language: 'ja' },
    { topic: 'フィットネスと身体的健康', language: 'ja' },
    { topic: '時間の管理', language: 'ja' },
    { topic: '自己認識', language: 'ja' },
    { topic: '霊的探求', language: 'ja' },
    { topic: '社会的適応力', language: 'ja' },
    { topic: '自己表現', language: 'ja' },
    { topic: 'キャリアの満足度', language: 'ja' },
    { topic: 'ファイナンシャルリテラシー', language: 'ja' },
    { topic: '家族の調和', language: 'ja' },
    { topic: '冒険と探機', language: 'ja' },
    { topic: 'スピリチュアルヒーリング', language: 'ja' },
    { topic: '才能の開発', language: 'ja' },
    { topic: '起業の機会', language: 'ja' },
    { topic: '客観的な達成', language: 'ja' },
    { topic: 'バランスと調和', language: 'ja' },
    { topic: 'コミュニティの参加', language: 'ja' },
    { topic: '家族のサポート', language: 'ja' },
    { topic: '内在的な叡智', language: 'ja' },
    { topic: '感情表現', language: 'ja' },
    { topic: '環境意識', language: 'ja' },
    { topic: '心身の調和', language: 'ja' },
    { topic: 'スピリチュアルな導き', language: 'ja' },
    { topic: '健康な習慣', language: 'ja' },
    { topic: 'チームの協力', language: 'ja' },
    { topic: '自己ケア', language: 'ja' },
    { topic: '仕事への献身', language: 'ja' },
  ],
  [
    { topic: '健康', language: 'zh-Hant' },
    { topic: '家庭', language: 'zh-Hant' },
    { topic: '社交關係', language: 'zh-Hant' },
    { topic: '學業', language: 'zh-Hant' },
    { topic: '旅遊', language: 'zh-Hant' },
    { topic: '心靈成長', language: 'zh-Hant' },
    { topic: '個人成長', language: 'zh-Hant' },
    { topic: '情感平衡', language: 'zh-Hant' },
    { topic: '自信與自尊', language: 'zh-Hant' },
    { topic: '內在平靜', language: 'zh-Hant' },
    { topic: '社會影響力', language: 'zh-Hant' },
    { topic: '人際溝通', language: 'zh-Hant' },
    { topic: '靈性連結', language: 'zh-Hant' },
    { topic: '存在意義', language: 'zh-Hant' },
    { topic: '靈感與創造力', language: 'zh-Hant' },
    { topic: '心理與情緒健康', language: 'zh-Hant' },
    { topic: '人際關係', language: 'zh-Hant' },
    { topic: '教育發展', language: 'zh-Hant' },
    { topic: '健身與體能', language: 'zh-Hant' },
    { topic: '時間管理', language: 'zh-Hant' },
    { topic: '自我認知', language: 'zh-Hant' },
    { topic: '心靈探索', language: 'zh-Hant' },
    { topic: '社會適應能力', language: 'zh-Hant' },
    { topic: '自我表達', language: 'zh-Hant' },
    { topic: '職業滿足度', language: 'zh-Hant' },
    { topic: '理財能力', language: 'zh-Hant' },
    { topic: '家庭和諧', language: 'zh-Hant' },
    { topic: '冒險與探索', language: 'zh-Hant' },
    { topic: '心靈療癒', language: 'zh-Hant' },
    { topic: '才藝發展', language: 'zh-Hant' },
    { topic: '創業機會', language: 'zh-Hant' },
    { topic: '客觀實現', language: 'zh-Hant' },
    { topic: '平衡與調和', language: 'zh-Hant' },
    { topic: '社區參與', language: 'zh-Hant' },
    { topic: '家庭支持', language: 'zh-Hant' },
    { topic: '內在智慧', language: 'zh-Hant' },
    { topic: '情感表達', language: 'zh-Hant' },
    { topic: '環境意識', language: 'zh-Hant' },
    { topic: '身心調和', language: 'zh-Hant' },
    { topic: '靈性導向', language: 'zh-Hant' },
    { topic: '健康習慣', language: 'zh-Hant' },
    { topic: '團隊合作', language: 'zh-Hant' },
    { topic: '自我關愛', language: 'zh-Hant' },
    { topic: '敬業精神', language: 'zh-Hant' },
  ],
];

export async function migrate() {
  await Promise.all(
    prebuilt.flatMap((group) =>
      group.map(async (item) => {
        await PredictTopic.upsert({ ...item });
      }),
    ),
  );
}
